### PR TITLE
fix: Resolve whatBump is not a function error

### LINKED ISSUE #101: getting ERROR whatBump is not a function
Here is the output: 

```sh
> cross-env GITHUB_TOKEN=$GITHUB_TOKEN release-it

✔ npm run lint
ERROR whatBump is not a function
 ELIFECYCLE  Command failed with exit code 1.
```

`.release-it.json`: 
```json
{
  "hooks": {
    "before:init": [
      "npm run lint"
    ],
    "after:bump": [
      "npm run build"
    ]
  },
  "git": {
    "commitMessage": "chore: release v${version}",
    "requireCleanWorkingDir": true,
    "tagAnnotation": "Release v${version}",
    "tagName": "v${version}"
  },
  "github": {
    "release": true,
    "draft": true,
    "releaseName": "v${version}"
  },
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": {
        "name": "conventionalcommits",
        "types": [
          {
            "type": "feat",
            "section": "Features"
          },
          {
            "type": "fix",
            "section": "Bug Fixes"
          },
          {
            "type": "perf",
            "section": "Performance Updates"
          },
          {
            "type": "a11y",
            "section": "Accessibility"
          },
          {
            "type": "refactor",
            "section": "Refactors"
          },
          {
            "type": "style",
            "section": "Stylistic Updates"
          }
        ]
      },
      "infile": "CHANGELOG.md"
    }
  }
}

```

and related packages:
```json
{
  "@commitlint/cli": "^19.5.0",
  "@commitlint/config-conventional": "^19.5.0",
  "@release-it/conventional-changelog": "^9.0.0",
  "release-it": "^17.9.0",
}
```

### LINKED ISSUE #103: ERROR whatBump is not a function
After upgrade to 17.10
https://github.com/taiga-family/configurations/pull/673

I have failed job

https://github.com/taiga-family/configurations/actions/runs/11384045613/job/31670932627

image

my release it config:
https://github.com/taiga-family/configurations/blob/main/projects/release-it-config/index.js

### PR DESCRIPTION
**Pull request by oluwatobiss**
This PR does the following:
- Resolve the `ERROR whatBump is not a function` error by resolving the pending `preset` promise and passing the appropriate `whatBump` argument to `bumper.bump()`.
- Allow using any config file to optionally configure `release-it` to skip releasing a version. (Any accepted variation of a `whatBump: false` configuration option would do the job.

**`.release-it.json` Example**

```json
{
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": {
        "name": "conventionalcommits"
      },
      "whatBump": false
    }
  }
}
```

**`.release-it.js` Example**

```js
module.exports = {
  plugins: {
    "@release-it/conventional-changelog": {
      preset: {
        name: "conventionalcommits",
      },
      whatBump: false,
    }
  }
}
```

<details>
<summary><strong>Passing test's result</strong></summary>

```bash

$ npm run test

> @release-it/conventional-changelog@9.0.1 test
> node --test test.js

✔ should generate changelog using recommended bump (minor) (4839.2414ms)
✔ should generate changelog using recommended bump (patch) (2408.4955ms)
✔ should support tag suffix (2023.5232ms)
✔ should respect --no-increment and return previous, identical changelog (3402.4726ms)
✔ should ignore recommended bump (option) (2069.2052ms)
✔ should use provided pre-release id (1880.802ms)
- Git commit
✔ Git commit
- Git tag
✔ Git tag
- Git commit
✔ Git commit
- Git tag
✔ Git tag
- Git commit
✔ Git commit
- Git tag
✔ Git tag
- Git commit
✔ Git commit
- Git tag
✔ Git tag
✔ should follow conventional commit strategy with prereleaase (6971.9425ms)
✔ should use provided pre-release id (pre-release continuation) (1997.6218ms)
✔ should use provided pre-release id (next pre-release) (1672.1806ms)
✔ should use recommended bump (after pre-rerelease) (1865.4596ms)
✔ should follow strict semver (pre-release continuation) (1931.4418ms)
✔ should follow strict semver (pre-release continuation, conventionalcommits) (1892.9996ms)
✔ should use provided increment (1562.8889ms)
✔ should use provided version (ignore recommended bump) (1402.5338ms)
✔ should not throw with Git plugin disabled (886.8307ms)
- Git tag
✔ Git tag
✔ should write and update infile (4177.3786ms)
✔ should reject if conventional bump passes error (1171.7179ms)
✔ should reject if conventional changelog has error (1179.4039ms)
✔ should not write infile in dry run (1311.7151ms)
✔ should not write infile if set to false (1382.9401ms)
✔ should not bump when recommended bump returns null (4800.0704ms)
✔ should not bump when whatBump === false (2380.4874ms)
﹣ should pass parserOpts and writerOpts (0.1167ms) # SKIP
ℹ tests 23
ℹ suites 0
ℹ pass 22
ℹ fail 0
ℹ cancelled 0
ℹ skipped 1
ℹ todo 0
ℹ duration_ms 55225.2853

```

</details>

Resolves #101, resolves #103

### CODE REVIEW

**Comment by webpro** [comment]
Thanks a lot, @oluwatobiss! This looks promising.

One thing I don't really like is the `"undefined"` string, how about the `false` boolean?

---

Would like a helping hand here, so cc-ing @ayZagen, @will-stone, @egilsster, @LinuCC, @splincode, @tefanobartoletti, @andi1984-ds, @janbiasi, @chris-dura, @Tomas2D. Any chance you could give this a shot:

```
npm install -D https://pkg.pr.new/@release-it/conventional-changelog@105.tgz
```

**Comment by oluwatobiss** [comment]
> Thanks a lot, @oluwatobiss! This looks promising.
> 
> One thing I don't really like is the `"undefined"` string, how about the `false` boolean?
> 
> Would like a helping hand here, so cc-ing @ayZagen, @will-stone, @egilsster, @LinuCC, @splincode, @tefanobartoletti, @andi1984-ds, @janbiasi, @chris-dura, @Tomas2D. Any chance you could give this a shot:
> 
> ```
> npm install -D https://pkg.pr.new/@release-it/conventional-changelog@105.tgz
> ```

Sure! `false` looks neater. I will update it now.

**Comment by oluwatobiss** [comment]
Updated!

**Comment by egilsster** [comment]
9.0.1 fixed most of our woes, but one project was still having issues. The version above solves those 🎉 thanks for addressing this!

**Comment by webpro** [comment]
Released [v9.0.2](https://github.com/release-it/conventional-changelog/releases/tag/9.0.2)

Thanks a lot @oluwatobiss, you saved all of us! 🙏
