### ISSUE TITLE
Cannot generate a release [v.10.0.2]

### ISSUE THREAD

**Issue by push1st1k** [release-it/conventional-changelog#126]
When I'm trying to generate a release via `npx release-it --no-git` it fails with the error:
```
ERROR whatBump is not a function
```

It looks like it was introduced with https://github.com/release-it/conventional-changelog/pull/124. 

Reverting to the previous version 10.0.1 resolves the issue.

**Comment by push1st1k** [comment]
Fixed by overriding 'conventional-changelog-conventionalcommits' version, as there was a much older installed (via '@commitlint/config-conventional' https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/package.json#L43) and loaded instead of the right one.

Adding this to the `package.json` solved the issue
```
   "resolutions": {
      "conventional-changelog-conventionalcommits": "^9.0.0"
   }
```
