### ISSUE TITLE
ERROR whatBump is not a function

### ISSUE THREAD

**Issue by splincode** [release-it/conventional-changelog#103]
After upgrade to 17.10
https://github.com/taiga-family/configurations/pull/673

I have failed job

https://github.com/taiga-family/configurations/actions/runs/11384045613/job/31670932627

<img width="632" alt="image" src="https://github.com/user-attachments/assets/39713b72-f2f9-4f4d-9d28-532b7de26b60">

my release it config:
https://github.com/taiga-family/configurations/blob/main/projects/release-it-config/index.js

**Comment by webpro** [comment]
Please check a recent PR which has a fix: https://github.com/release-it/conventional-changelog/pull/102#issuecomment-2417907155

Sorry, I'm on the road.

**Comment by splincode** [comment]
@webpro 
<img width="802" alt="image" src="https://github.com/user-attachments/assets/a89af55c-bc86-46c2-82f3-28857fdb1552">

**Comment by splincode** [comment]
@webpro fixed

**Comment by splincode** [comment]
@webpro sorry, it's really strange, but it doesn't work with 9.0.1
https://github.com/taiga-family/configurations/actions/runs/11436217536/job/31813178852?pr=682

<img width="1072" alt="image" src="https://github.com/user-attachments/assets/892ca727-9933-4297-8425-971442b4600b">

**Comment by stefanobartoletti** [comment]
I'm still having this issue even with `v9.0.1` too
